NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.myorg2.ch-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.myorg2.ch-cert.pem
    OrganizationalUnitIdentifier: peer
